### ISSUE TITLE
Does this program work in MacBook?

### ISSUE THREAD

**Issue by LittleWat** [davmre/gprf#1]
Dear @davmre 

Thank you for the nice implementation!

I tried to test your code but met some errors like below. I cannot solve this error...

> ➜  gprf git:(kwatanabe) ✗ python gprfopt.py --n=10000 --seed=0 --yd=50 --lscale=0.06 --obs_std=0.02 --noise_var=0.01 --method=l-bfgs-b  --local_dist=1.0 --nblocks=100 --task=x --maxsec=18000
> Traceback (most recent call last):
>   File "gprfopt.py", line 1, in <module>
>     from gprf import GPRF
>   File "/Users/ar-kohei.watanabe/Codes/gprf/gprf.py", line 16, in <module>
>     from treegp.gp import GP, GPCov, mcov,  prior_sample
>   File "/Users/ar-kohei.watanabe/Codes/treegp/treegp/gp.py", line 8, in <module>
>     import scikits.sparse.cholmod
> ImportError: dlopen(/Users/ar-kohei.watanabe/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/scikits/sparse/cholmod.so, 2): Symbol not found: _dpotrf_
>   Referenced from: /Users/ar-kohei.watanabe/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/scikits/sparse/../../../../libcholmod.dylib
>   Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib

If you know how to solve this, please tell me.
Thank you in advance.

**Comment by davmre** [comment]
I've only ever run it on Linux, though it should be possible to get working
on a Mac. It looks like something is up with your installation of cholmod
(probably installed as part of scikit-sparse), so I'd double check that,
but unfortunately I probably don't have any special expertise here. :-)
